CREATE TABLE helpingpaw.admin(username VARCHAR(45) PRIMARY KEY, adminid INT);
INSERT INTO helpingpaw.admin VALUES("christom",1);
INSERT INTO helpingpaw.admin VALUES("s.schauer",2);
INSERT INTO helpingpaw.admin VALUES("e.esguerra",3);
INSERT INTO helpingpaw.admin VALUES("barrythemanager",4);
INSERT INTO helpingpaw.admin VALUES("sarahtheassistant",5);
INSERT INTO helpingpaw.admin VALUES("jessabeller",6);
INSERT INTO helpingpaw.admin VALUES("delenramos",7);
INSERT INTO helpingpaw.admin VALUES("eHillman",8);
INSERT INTO helpingpaw.admin VALUES("bLopez",9);
INSERT INTO helpingpaw.admin VALUES("bonnieBill",10);
INSERT INTO helpingpaw.admin VALUES("admin11",11);
INSERT INTO helpingpaw.admin VALUES("emergencyAdmin",12);
INSERT INTO helpingpaw.admin VALUES("guestAdmin",13);
INSERT INTO helpingpaw.admin VALUES("davidtom",14);
INSERT INTO helpingpaw.admin VALUES("maryjoe",15);