CREATE TABLE helpingpaw.adopter(username VARCHAR(45) PRIMARY KEY, adoptedid INT);
INSERT INTO helpingpaw.adopter VALUES("mj300",1);
INSERT INTO helpingpaw.adopter VALUES("ronniem",2);
INSERT INTO helpingpaw.adopter VALUES("puppyluvr",3);
INSERT INTO helpingpaw.adopter VALUES("fossilfighter",4);
INSERT INTO helpingpaw.adopter VALUES("cp30",5);
INSERT INTO helpingpaw.adopter VALUES("djade16",6);
INSERT INTO helpingpaw.adopter VALUES("winchester.m",7);
INSERT INTO helpingpaw.adopter VALUES("sarahcoleman",8);
INSERT INTO helpingpaw.adopter VALUES("djramos",9);
INSERT INTO helpingpaw.adopter VALUES("meowmeow",10);
INSERT INTO helpingpaw.adopter VALUES("birdbrain",11);
INSERT INTO helpingpaw.adopter VALUES("birdsandthings",12);
INSERT INTO helpingpaw.adopter VALUES("ladybunny",13);
INSERT INTO helpingpaw.adopter VALUES("jessicarabbit",14);
INSERT INTO helpingpaw.adopter VALUES("furryfriend",15);