CREATE TABLE helpingpaw.seller (username VARCHAR(45) PRIMARY KEY, sellerid INT);
INSERT INTO helpingpaw.seller VALUES("puppyluver01",1);
INSERT INTO helpingpaw.seller VALUES("birdsandthings",2);
INSERT INTO helpingpaw.seller VALUES("argonaut2000",3);
INSERT INTO helpingpaw.seller VALUES("christom",4);
INSERT INTO helpingpaw.seller VALUES("lizhill",5);
INSERT INTO helpingpaw.seller VALUES("brandenL",6);
INSERT INTO helpingpaw.seller VALUES("toomanydogs",7);
INSERT INTO helpingpaw.seller VALUES("lizardlounge",8);
INSERT INTO helpingpaw.seller VALUES("hamsterhut",9);
INSERT INTO helpingpaw.seller VALUES("mgeller1989",10);
INSERT INTO helpingpaw.seller VALUES("monicalewis",11);
INSERT INTO helpingpaw.seller VALUES("jessramos",12);
INSERT INTO helpingpaw.seller VALUES("marykate",13);
INSERT INTO helpingpaw.seller VALUES("kitkatclub",14);
INSERT INTO helpingpaw.seller VALUES("rabbitsonrabbits",15);